#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<EOSQL
CREATE USER $DATABASE_USERNAME WITH PASSWORD '$DATABASE_PASSWORD';
CREATE DATABASE "$DATABASE_NAME";
GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO $DATABASE_USERNAME;
EOSQL